加KIP函式。
i3thuan5/KeSi pull request #58
Opened 2023-06-29 06:37 UTC by sih4sing5hong5

2023-06-30 01:59 UTC, a8568730 requested changes

2023-06-30 01:59 UTC, a8568730 commented on panpun.py
> +PANPUN = '1.5.0'
勞煩README加使用範例，感謝。

2023-06-30 03:35 UTC, sih4sing5hong5 commented on panpun.py
> +PANPUN = '1.5.0'
b7c3109

2023-07-03 02:37 UTC, a8568730 requested changes

2023-07-03 02:37 UTC, a8568730 commented on README.md
> +Ku("看--起-來chiâⁿ媠。").KIP().hanlo    # '看--起-來tsiânn媠。'
多謝。Koh勞煩補：
> 1.4.3版以前POJ轉KIP函式號做TL()；1.5.0版以後改號做KIP()，兩款函式lóng支援。未來KIP()會取代TL()。

2023-07-04 04:09 UTC, sih4sing5hong5 commented on README.md
> +Ku("看--起-來chiâⁿ媠。").KIP().hanlo    # '看--起-來tsiânn媠。'
1689570 kah eb9697b 補--ah

2023-07-06 03:30 UTC, a8568730 commented on README.md
> +Ku("看--起-來chiâⁿ媠。").KIP().hanlo    # '看--起-來tsiânn媠。'
感謝！

2023-07-06 03:32 UTC, a8568730 approved these changes
🎉

2023-07-06 03:32 UTC, merged